### ISSUE TITLE
Event Packets May Not Have Even Number of Words

### ISSUE THREAD

**Issue by ksmith0** [ComPair/ComPairDAQ#4]
A restriction was added in the event packet class that each event packet has an even number of words. The subsystem may provide an odd number of words and as such the event packet would be odd.

https://github.com/ComPair/ComPairDAQ/blob/ee471cf4b1a1e17d60c2e02a8ce1c62cc71d018a/source/ComPairEventPacket.cxx#L8-L13

**Comment by lucasparker** [comment]
It seems like the `uint16_t` type probably isn't the one to base parsing off of, as packets can have an odd number of bytes. I'm going to update the parse methods to accept `vector<uint8_t>` today

**Comment by lucasparker** [comment]
Closing after merging in `uint16_to_uint8` branch
